
TrinketCDsProfile = {
	["SWITCHES"] = {
		["SHOW_DECIMALS"] = 0,
		["USE_ON_CLICK"] = 1,
		["FORCE30"] = 0,
		["COMBAT_ONLY"] = 0,
		["STACKS_BOTTOM"] = 0,
		["HIDE_READY"] = 0,
	},
	["ITEMS"] = {
		[6] = {
			["CD_SIZE"] = 40,
			["POS_Y"] = -210,
			["ZOOM"] = 0,
			["ICON_SIZE"] = 35,
			["POS_X"] = 184.144775390625,
			["SHOW_ILVL"] = 0,
			["SHOW"] = 0,
			["STACKS_SIZE"] = 50,
			["EDGE_SIZE"] = 10,
			["ILVL_SIZE"] = 20,
			["BORDER_MARGIN"] = 1,
		},
		[13] = {
			["CD_SIZE"] = 40,
			["POS_Y"] = -210,
			["ZOOM"] = 0,
			["ICON_SIZE"] = 35,
			["POS_X"] = -38,
			["SHOW_ILVL"] = 1,
			["SHOW"] = 1,
			["STACKS_SIZE"] = 50,
			["EDGE_SIZE"] = 10,
			["ILVL_SIZE"] = 20,
			["BORDER_MARGIN"] = 1,
		},
		[8] = {
			["CD_SIZE"] = 40,
			["POS_Y"] = -210,
			["ZOOM"] = 0,
			["ICON_SIZE"] = 35,
			["POS_X"] = -76,
			["SHOW_ILVL"] = 0,
			["SHOW"] = 1,
			["STACKS_SIZE"] = 50,
			["EDGE_SIZE"] = 10,
			["ILVL_SIZE"] = 20,
			["BORDER_MARGIN"] = 1,
		},
		[10] = {
			["CD_SIZE"] = 40,
			["POS_Y"] = -210,
			["ZOOM"] = 0,
			["ICON_SIZE"] = 35,
			["POS_X"] = 76,
			["SHOW_ILVL"] = 0,
			["SHOW"] = 1,
			["STACKS_SIZE"] = 50,
			["EDGE_SIZE"] = 10,
			["ILVL_SIZE"] = 20,
			["BORDER_MARGIN"] = 1,
		},
		[15] = {
			["CD_SIZE"] = 40,
			["POS_Y"] = -210,
			["ZOOM"] = 0,
			["ICON_SIZE"] = 40,
			["POS_X"] = 26.94677734375,
			["SHOW_ILVL"] = 0,
			["SHOW"] = 0,
			["STACKS_SIZE"] = 50,
			["EDGE_SIZE"] = 10,
			["ILVL_SIZE"] = 20,
			["BORDER_MARGIN"] = 1,
		},
		[14] = {
			["CD_SIZE"] = 40,
			["POS_Y"] = -210,
			["ZOOM"] = 0,
			["ICON_SIZE"] = 35,
			["POS_X"] = 38,
			["SHOW_ILVL"] = 1,
			["SHOW"] = 1,
			["STACKS_SIZE"] = 50,
			["EDGE_SIZE"] = 10,
			["ILVL_SIZE"] = 20,
			["BORDER_MARGIN"] = 1,
		},
		[16] = {
			["CD_SIZE"] = 40,
			["POS_Y"] = -210,
			["ZOOM"] = 0,
			["ICON_SIZE"] = 35,
			["POS_X"] = 95,
			["SHOW_ILVL"] = 0,
			["SHOW"] = 0,
			["STACKS_SIZE"] = 50,
			["EDGE_SIZE"] = 10,
			["ILVL_SIZE"] = 20,
			["BORDER_MARGIN"] = 1,
		},
		[11] = {
			["CD_SIZE"] = 40,
			["POS_Y"] = -210,
			["ZOOM"] = 0,
			["ICON_SIZE"] = 35,
			["POS_X"] = 0,
			["SHOW_ILVL"] = 0,
			["SHOW"] = 1,
			["STACKS_SIZE"] = 50,
			["EDGE_SIZE"] = 10,
			["ILVL_SIZE"] = 20,
			["BORDER_MARGIN"] = 1,
		},
	},
}
